---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: hashicups
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./application
  prune: true
  sourceRef:
    kind: GitRepository
    name: hashicups
  targetNamespace: default